defop  "ULD", ureg, ureg;
defop  "FLD", freg, ureg;
defop  "UST", ureg, ureg;
defop  "FST", ureg, freg;
defop "UIMM", ureg,  imm;
defop "FIMM", freg, fimm;
defop "UMOV", ureg, ureg;
defop "FMOV", freg, freg;
defop  "U2F", freg, ureg;
defop  "I2F", freg, ureg;
defop  "F2U", ureg, freg;
defop  "F2I", ureg, freg;
defop   "BT", iimm;
defop   "BF", iimm;
defop  "UEQ", ureg, ureg;
defop  "FEQ", freg, freg;
defop  "UGT", ureg, ureg;
defop  "IGT", ureg, ureg;
defop  "FGT", freg, freg;
defop  "ULT", ureg, ureg;
defop  "ILT", ureg, ureg;
defop  "FLT", freg, freg;
defop "UADD", ureg, ureg;
defop "FADD", freg, freg;
defop "USUB", ureg, ureg;
defop "FSUB", freg, freg;
defop "UMUL", ureg, ureg;
defop "IMUL", ureg, ureg;
defop "FMUL", freg, freg;
defop "UDIV", ureg, ureg;
defop "IDIV", ureg, ureg;
defop "FDIV", freg, freg;
defop "CALL", ureg, ureg;
defop "STOP", ureg;
